tasks:
  - command: code --install-extension redhat.java && code --install-extension vscjava.vscode-java-debug sleep 40 && code --install-extension revaturePro.revature-labs
  - command: for i in {1..3}; do code --uninstall-extension vscjava.vscode-java-test; sleep 15; done
  - command: for i in {1..6}; do chmod 600 ~/.ssh/id_rsa && chmod 644 ~/.ssh/id_rsa.pub && ssh-keyscan github.com >> ~/.ssh/known_hosts; sleep 20; done
  - command: git remote set-url origin git@github.com:LilLemonJr/LilLemonJr-pep-project.git && sed "s/\r$//" commit-command.sh | bash